### ISSUE TITLE
JSON dependency fails to build

### ISSUE THREAD

**Issue by JSybrandt** [rlue/jekyll-solana#2]
The version of JSON gem does not work with latest ruby (2.4)
Using bundler 1.13.7
Gem::Ext::BuildError: ERROR: Failed to build gem native extension
...
An error occurred while installing json (1.8.6), and Bundler cannot continue.

Is it possible to remove / change this dependency to allow support for current versions?

**Comment by rlue** [comment]
That's odd — I'm running Ruby 2.4.0 and I don't have any problems installing that gem (FWIW I'm also on bundler 1.15.4). 

In any case, if you're sure the issue is with that particular version of the `json` gem, then an easy fix is to delete `Gemfile.lock` and run `bundle install` again. Come to think of it, this repo really doesn't need the `Gemfile.lock` file anyway, so I've just removed it. Thanks for the idea.

To expound on the issue, this theme only references one gem, which is the [`github-pages` meta-gem](https://github.com/github/pages-gem) (see the [Gemfile](https://github.com/rlue/jekyll-solana/blob/master/Gemfile)). The `json` gem you're referencing is required as a dependency of `activesupport`.

A lot of people seem to have run into [the same error you did](https://github.com/flori/json/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20builderror%20), extending as far back as 2015 (Ruby 2.2 and json 1.8.3). If you continue to have problems with this gem, try consulting those threads?
